[Command]
alias = "nv"
program = "node"
args = "-v"

[Command]
alias = "n"
program = "neofetch"
args = ""

[Command]
alias = "cc"
program = "cargo"
args = "check"

[Command]
alias = "gs"
program = "git"
args = "status"

[Command]
alias = "ci"
program = "cargo"
args = "install --path ."